let classRoom = [
    {
        age:20,
        name:"김하경",
        gender:'여자',
        married:false,
        hobbies:['게임','그림그리기','음악듣기'],
        thumbnailFileName:"김하경.png"
    },
    {
        gender:'남자',
        name:"성대한",
        age:28,
        married:false,
        hobbies:['그림그리기','게임'],
        thumbnailFileName:"성대한.png"
    },
    {
        name:"이선영",
        age:24,
        gender:'여자',
        married:false,
        hobbies:['그림그리기','게임','인형만들기'],
        thumbnailFileName:"이선영.png"
    },
    {
        name:"장예원",
        age:29,
        gender:'여자',
        married:false,
        hobbies:['그림그리기','음악듣기'],
        thumbnailFileName:"장예원.png"
    },
    {
        name:"정선민",
        age:29,
        gender:'여자',
        married:false,
        hobbies:['독서','게임','운동'],
        thumbnailFileName:"정선민.png"
    },
    {
        name:"김현아",
        age:22,
        gender:'여자',
        married:false,
        hobbies:['음악듣기','산책하기','레고만들기'],
        thumbnailFileName:"김현아.png"
    },
    {
        name:"김예림",
        age:29,
        gender:'여자',
        married:false,
        hobbies:['독서','야구시청'],
        thumbnailFileName:"김예림.png"
    },
    {
        name:"이효은",
        age:20,
        gender:'여자',
        married:false,
        hobbies:['산책하기','음악듣기'],
        thumbnailFileName:"이효은.png"
    },
    {
        name:"백민선",
        age:31,
        gender:'여자',
        married:false,
        hobbies:['영화보기','네일아트'],
        thumbnailFileName:"백민선.png"
    },
    {
        name:"함국주",
        age:29,
        gender:'남자',
        married:true,
        hobbies:['캠핑하기','배드민턴','러닝하기','요리하기'],
        thumbnailFileName:"함국주.png"
    },
    {
        name:"박민주",
        age:32,
        gender:'여자',
        married:true,
        hobbies:['웨이트','롤','요리하기','야구시청','유튜브시청'],
        thumbnailFileName:"박민주.png"
    },
    {
        name:"윤희정",
        age:44,
        gender:'여자',
        married:false,
        hobbies:['웹소설듣기','등산하기','궁 관람','미술관 관람','디오라마 조립'],
        thumbnailFileName:"윤희정.png"
    },
    {
        name:"최선미",
        age:41,
        gender:'여자',
        married:true,
        hobbies:['수영하기','식물키워','스노쿨링','낚시하기','캠핑하기','스노우보드'],
        thumbnailFileName:"최선미.png"
    },
    {
        name:"김가온",
        age:19,
        gender:'여자',
        married:false,
        hobbies:['게임하기','갈틱폰','말랑이하기','큰 마트 가기'],
        thumbnailFileName:"김가온.png"
    },
    {
        name:"안정현",
        age:25,
        gender:'남자',
        married:false,
        hobbies:['영화감상','그림그리기','요리하기','스케이트타기'],
        thumbnailFileName:"안정현.png"
    },
    {
        name:"최윤성",
        age:28,
        gender:'남자',
        married:false,
        hobbies:['기타치기','러닝하기','만화보기','게임하기'],
        thumbnailFileName:"최윤성.png"
    },
    {
        name:"배수정",
        age:38,
        gender:'여자',
        married:false,
        hobbies:['독서','뮤지컬보기'],
        thumbnailFileName:"배수정.png"
    },
    {
        name:"유채린",
        age:24,
        gender:'여자',
        married:false,
        hobbies:['여행가기','요리하기','블로그','음악듣기'],
        thumbnailFileName:"유채린.png"
    }
]